/**
 * Recipe Generator — Downloadable Recipe Bundle
 *
 * Generates a markdown document from a RecipeBundle that contains
 * all config files for drop-in use with the Sovereign Manifesto.
 *
 * VERSION: 1.0.0
 */

import type { RecipeBundle } from '../config/signal-watch-recipe'

// =============================================================================
// MARKDOWN GENERATOR
// =============================================================================

/**
 * Generate a downloadable markdown document from a RecipeBundle.
 * The output is structured for agentic IDE consumption.
 */
export function generateRecipeMarkdown(recipe: RecipeBundle): string {
  const timestamp = new Date().toISOString().slice(0, 10)

  let markdown = `# ${recipe.name} — Recipe Bundle

> **Companion to:** Sovereign Manifesto: ${recipe.name}
> **Version:** ${recipe.version}
> **Generated:** ${timestamp}

## What This Is

This file contains the complete configuration for ${recipe.name} — ${recipe.description}. Each code block below is a file. Together with the Sovereign Manifesto, they define a buildable application.

## How To Use

1. Open an agentic IDE (Claude Code, Cursor, Windsurf)
2. Create a new project directory
3. Drop this file AND the Sovereign Manifesto HTML into the directory
4. Prompt: "Read both files. The Manifesto is the architectural contract. The Recipe Bundle contains the config files. Scaffold Phase 1, then apply the recipe configs. Build it."
5. Review. Approve. Repeat for Phases 2-4.

---

`

  // Track whether we've added the knowledge layer header
  let knowledgeHeaderAdded = false

  // Add each file as a markdown section with code block
  for (const file of recipe.files) {
    // Detect knowledge files and add section header before the first one
    const isKnowledgeFile = file.filename.startsWith('knowledge/')
    if (isKnowledgeFile && !knowledgeHeaderAdded) {
      markdown += `## Knowledge Layer

> These markdown files are loaded as context during analysis.
> They shape HOW the system thinks, not WHAT it monitors.
> Replace them with your domain expertise, a RAG endpoint,
> a Notion export, or any markdown source. The pipeline reads it the same way.

---

`
      knowledgeHeaderAdded = true
    }

    // Use markdown language tag for .md files, typescript for others
    const languageTag = file.filename.endsWith('.md') ? 'markdown' : 'typescript'

    markdown += `## ${file.filename}
> ${file.description}

\`\`\`${languageTag}
${file.content.trim()}
\`\`\`

---

`
  }

  // Footer
  markdown += `
## Build Phases

- **Phase 1:** Structural Skeleton (Pipeline, Zones, Routing, Telemetry)
- **Phase 2:** Intelligence Layer (Cognitive Router, Model Abstraction, Jidoka)
- **Phase 3:** Self-Improvement Loop (Skill Flywheel, The Ratchet)
- **Phase 4:** Recipe Polish (Views, Theme, Seed Data, Voice, Knowledge)

---

*Generated by [The Grove Foundation](https://the-grove.ai) • Licensed under CC BY 4.0*
`

  return markdown
}

// =============================================================================
// DOWNLOAD TRIGGER
// =============================================================================

/**
 * Trigger download of the recipe markdown as a .md file.
 */
export function downloadRecipe(appName: string, markdown: string): void {
  const blob = new Blob([markdown], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `recipe-bundle-${slugify(appName)}.md`
  a.click()
  URL.revokeObjectURL(url)
}

// =============================================================================
// HELPERS
// =============================================================================

function slugify(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}
